### 1.Cargue los datos en un dataframe

In [11]:
import kagglehub
import pandas as pd
import glob

# Descargar el dataset (sin extensión en el slug)
path = kagglehub.dataset_download("parulpandey/forbes-highest-paid-athletes-19902019")

# Encontrar el archivo CSV automáticamente
csv_files = glob.glob(f"{path}/**/*.csv", recursive=True)
print("Archivos encontrados:", csv_files)

# Cargar el primer CSV encontrado
df = pd.read_csv(csv_files[0])
df.head()

Archivos encontrados: ['/home/sebastian/.cache/kagglehub/datasets/parulpandey/forbes-highest-paid-athletes-19902019/versions/10/Forbes Richest Atheletes (Forbes Richest Athletes 1990-2020).csv']

,S.NO,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,1,Mike Tyson,USA,1,NaN,boxing,1990,28.6
1,2,Buster Douglas,USA,2,NaN,boxing,1990,26.0
2,3,Sugar Ray Leonard,USA,3,NaN,boxing,1990,13.0
3,4,Ayrton Senna,Brazil,4,NaN,auto racing,1990,10.0
4,5,Alain Prost,France,5,NaN,auto racing,1990,9.0

### 2. Identificar el tipo de datos de cada variable.

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   S.NO                  301 non-null    int64
 1   Name                  301 non-null    str
 2   Nationality           301 non-null    str
 3   Current Rank          301 non-null    int64
 4   Previous Year Rank    277 non-null    str
 5   Sport                 301 non-null    str
 6   Year                  301 non-null    int64
 7   earnings ($ million)  301 non-null    float64
dtypes: float64(1), int64(3), str(4)
memory usage: 18.9 KB

### 3. Calcular estadísticas básicas para cada variable. Sea de posición, dispersión y tendencia central. Para el caso de variables categóricas calcule la moda.

In [66]:
df.describe(include='all')

,S.NO,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million),earning
count,301.000000,301,301,301.000000,277,301,301.000000,301.000000,301
unique,NaN,82,22,NaN,36,29,NaN,NaN,5
top,NaN,Michael Jordan,USA,NaN,>10,Basketball,NaN,NaN,Muy Bajo
freq,NaN,19,206,NaN,36,54,NaN,NaN,61
mean,151.000000,NaN,NaN,5.448505,NaN,NaN,2005.122924,45.516279,NaN
std,87.035433,NaN,NaN,2.850995,NaN,NaN,9.063563,33.525337,NaN
min,1.000000,NaN,NaN,1.000000,NaN,NaN,1990.000000,8.100000,NaN
25%,76.000000,NaN,NaN,3.000000,NaN,NaN,1997.000000,24.000000,NaN
50%,151.000000,NaN,NaN,5.000000,NaN,NaN,2005.000000,39.000000,NaN
75%,226.000000,NaN,NaN,8.000000,NaN,NaN,2013.000000,59.400000,NaN
max,301.000000,NaN,NaN,10.000000,NaN,NaN,2020.000000,300.000000,NaN

### 4. Transforme la variable “earnings” en una variable categórica implementando intervalos de clase. Calcule la frecuencia de cada clase.

In [28]:
df['earning'], limites = pd.qcut(df['earnings ($ million)'], q=5, labels=['Muy Bajo', 'Bajo', 'Medio', 'Alto', 'Muy Alto'],retbins=True)
print(limites)
df['earning'].value_counts()

[  8.1  21.   32.5  45.   64.8 300. ]

earning
Muy Bajo    61
Bajo        60
Medio       60
Alto        60
Muy Alto    60
Name: count, dtype: int64

### 5. Conteste las siguientes preguntas:

#### a) ¿Quién es la persona que más dinero ganó en un año?

In [29]:
df['Name'][df['earnings ($ million)'].idxmax()]

'Floyd Mayweather'

#### b) ¿Cuál es el deporte que más se repite dentro de la lista?

In [32]:
deporte_moda = df['Sport'].mode()[0]
print(f"El deporte más común es: {deporte_moda}")

El deporte más común es: Basketball

#### c) ¿Cuál es el deporte donde más dinero se gana?

In [42]:
deporte_que_mas_gana_promedio = df.groupby('Sport')['earnings ($ million)'].mean().idxmax()
print(f"El deporte que más gana en promedio es: {deporte_que_mas_gana_promedio}")

deporte_que_mas_gana_total = df.groupby('Sport')['earnings ($ million)'].sum().idxmax()
print(f"El deporte que más gana en total es: {deporte_que_mas_gana_total}")

El deporte que más gana en promedio es: MMA
El deporte que más gana en total es: Basketball

#### d) Si quisiera apostar a un jugador de Basketball según su ranking. ¿A cuál debería apostar?

In [79]:
basket_df = df[df['Sport'] == 'Basketball']
mejor_promedio = basket_df.groupby('Name')['Current Rank'].mean().sort_values(ascending=True)
top_basketball = mejor_promedio.head(1)
print(mejor_promedio)
print(f"{top_basketball.index[0]} tiene el ranking más alto en basketball con el Ranking Promedio de {top_basketball.iloc[0]}")

Name
Michael Jordan      2.100000
LeBron James        4.555556
Shaq O'Neal         5.000000
Shaquille O'Neal    5.333333
Kevin Durant        6.800000
Kobe Bryant         7.166667
Grant Hill          7.333333
Kevin Garnett       7.666667
Stephen Curry       7.750000
Patrick Ewing       8.500000
Dennis Rodman       9.000000
James Harden        9.000000
Name: Current Rank, dtype: float64
Michael Jordan tiene el ranking más alto en basketball con el Ranking Promedio de 2.1

#### e) ¿Para qué áreas de negocio puede ser útil el análisis de este dataset? ¿Qué decisiones puede ayudar a tomar?

**Esto puede util para areas de negocios deportivos o casa de apuestas, temas de marking, etc**

#### 6. Entregue conclusiones sobre lo desarrollado. Comente los descubrimientos que más le sorprendieron, lo que más le costó y qué otra información le gustaría extraer de los datos trabajados.

**La conclusión es que se obtuve una gran cantidad de datos, como por ejemplo que la nacionalidad que más se repite es USA, el deporte más jugado es Basketball, en promedio de ganancias de los deportistas es 45.51 millones de dolares,etc.**

**Lo que más me costo fue aplicar funciones de pandas en cadena, tales como la de obtener el top de basketball por ranking y el deporte en donde más se gana**