In [51]:
import numpy as np
import pandas as pd
np.random.seed(1)

#### Crea un array NumPy con datos numéricos de tu interés (ejemplo: notas de cursos, puntuaciones de juegos, etc.).

In [52]:
array = np.random.randint(101, size=(100))
array

array([ 37,  12,  72,   9,  75,   5,  79,  64,  16,   1,  76,  71,   6,
        25,  50,  20,  18,  84,  11,  28,  29,  14,  50,  68,  87,  87,
        94,  96,  86,  13,   9,   7,  63,  61,  22,  57,   1,   0,  60,
        81,   8,  88,  13,  47,  72,  30,  71,   3,  70,  21,  49,  57,
         3,  68,  24,  43,  76,  26,  52,  80,  41,  82,  15,  64,  68,
        25,  98,  87,   7,  26,  25,  22,   9,  67,  23, 100,  27,  37,
        57,  83,  38,   8,  32,  34,  10,  23,  15,  87,  25,  71,  92,
        74,  62,  46,  32,  88,  23,  55,  65,  77])

#### Crea un DataFrame de Pandas con al menos 2 columnas y 5 filas (ejemplo: tu nombre y notas de distintas asignaturas).

In [53]:
df = pd.DataFrame({
    'Lenguaje': np.round(np.random.uniform(1, 7, 5), 1),
    'Matematicas': np.round(np.random.uniform(1, 7, 5),1)
})
df

   Lenguaje  Matematicas
0       3.5          6.7
1       1.3          4.5
2       4.2          6.4
3       5.0          1.8
4       4.1          1.8

In [59]:
columns = ['Lenguaje', 'Matematicas', 'Historia', 'Ed. Fisica', 'Artes', 'Musica']

df = pd.DataFrame()
for col in columns:
    df[col] = np.round(np.random.uniform(1, 7, 1000), 1)
    
df

     Lenguaje  Matematicas  Historia  Ed. Fisica  Artes  Musica
0         1.7          1.0       3.2         5.5    6.8     1.8
1         2.2          3.4       6.2         3.7    3.3     3.6
2         5.6          5.5       3.7         3.6    6.0     5.3
3         2.8          6.2       2.8         3.1    5.3     6.6
4         4.8          3.7       2.3         6.5    3.4     6.1
..        ...          ...       ...         ...    ...     ...
995       3.3          3.3       2.1         3.4    4.1     2.8
996       3.8          6.2       4.8         2.8    1.0     5.7
997       1.6          4.8       2.9         2.9    3.8     1.6
998       5.6          6.9       3.1         3.4    2.0     5.0
999       3.5          2.3       3.2         5.1    6.3     6.3

[1000 rows x 6 columns]

In [58]:
df.describe()

,Lenguaje,Matematicas,Historia,Ed. Fisica,Artes,Musica
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.994629,4.002771,3.995419,4.003003,3.996609,4.000494
std,1.736829,1.732272,1.734063,1.728780,1.731102,1.728040
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.500000,2.500000,2.500000,2.500000,2.500000,2.500000
50%,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
75%,5.500000,5.500000,5.500000,5.500000,5.500000,5.500000
max,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000